// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solar1TesterSorterLableGenerator.DatabaseHelper;

namespace Solar1TesterSorterLableGenerator.Migrations
{
    [DbContext(typeof(TesterSorterDbContext))]
    [Migration("20231125124119_editBin")]
    partial class editBin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Solar1TesterSorterLableGenerator.DatabaseHelper.BinRecipeModel", b =>
                {
                    b.Property<int>("BinRecipeModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BinNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Print")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BinRecipeModelID");

                    b.ToTable("Bs_BinRecipeModel");
                });
#pragma warning restore 612, 618
        }
    }
}
